export const ONLINE_ORDER = 'ONLINE_ORDER';

export const ONLINE_ORDER_MULTIPLE = 'ONLINE_ORDER_MULTIPLE';

export const GET_MY_ORDERS = 'GET_MY_ORDERS';

export const CANCEL_ORDER = 'CANCEL_ORDER';

export const ONLINE_ORDER_COD = 'ONLINE_ORDER_COD';

export const ONLINE_ORDER_MULTIPLE_COD = 'ONLINE_ORDER_MULTIPLE_COD';

export const GET_LOCATION = 'GET_LOCATION';

export const LOADING_START = 'LOADING_START';

export const LOADING_END = 'LOADING_END';